### ISSUE TITLE
selecting images with Media Manager

### ISSUE THREAD

**Issue by betteryouthanme** [JoomJunk/Slideset#14]
to make it more user-friendly and easier to understand as i had some troubles with selecting images
(wanted to add images outside the slideset image folder)

**Comment by C-Lodder** [comment]
Problem being is the media manager by default only allows you to access files within the "images" folder. If I allow users to choose images outside the images folder, then they will no doubt have issues when defining their paths and I'll get a load of emails for support on this ;)

Unfortunately, I'm going to keep this as it is, however I'll try adding some instructions in the settings to make it easier

**Comment by C-Lodder** [comment]
https://github.com/JoomJunk/Slideset/commit/4ddb2eaf0e5c6c534a134c8599db30d94468c32f
