### ISSUE TITLE
responsive settings are messed up

### ISSUE THREAD

**Issue by betteryouthanme** [JoomJunk/Slideset#19]
I have following setup:
Options: Items=2
Responsive: Items (Small screen)=1
others responsive values are empty

Somehow it displays 1 image in large view but 2 in small screen?
The other way round it works fine ;)

**Comment by C-Lodder** [comment]
@betteryouthanme - If you use 1 of the responsive parameters, you need to assign value for the other ones (medium, large etc). There will be a bit of code confusion for me, so I'll update the instructions for this

**Comment by C-Lodder** [comment]
https://github.com/JoomJunk/Slideset/commit/49ca775cf3516987eb64a85b40d2af75068456d4
